/**
 * SQLite persistence via tauri-plugin-sql, with Drizzle as the ORM.
 *
 * - Schema lives in ./schema.ts; migrations are generated by drizzle-kit
 *   into /drizzle and applied here at startup (tracked in __migrations).
 * - Writes go through Drizzle's query builder (typed against the schema)
 *   executed over the plugin.
 * - Reads use plain `SELECT *` mapped by column NAME using Drizzle's
 *   table metadata. (The sqlite-proxy driver wants positional rows, but
 *   the plugin returns name-keyed objects — mapping by name is the only
 *   ordering-safe bridge, so selects deliberately bypass the proxy.)
 */
import Database from "@tauri-apps/plugin-sql";
import { drizzle } from "drizzle-orm/sqlite-proxy";
import {
  and,
  eq,
  getTableColumns,
  getTableName,
  inArray,
  notInArray,
  sql,
} from "drizzle-orm";
import type { SQLiteTable } from "drizzle-orm/sqlite-core";
import type {
  AppData,
  Exercise,
  PersonalRecord,
  Session,
  Split,
} from "../types";
import { loadData, mergeBuiltIns, STORAGE_KEY } from "../lib/store";
import type { Persistence } from "./persistence";
import * as t from "./schema";

const DB_URL = "sqlite:varg.db";

/** SQL string literal. Only used for values we control (migration names). */
function quote(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

/** The plugin rejects with a plain string as often as with an Error. */
function errorText(err: unknown): string {
  if (err instanceof Error) return err.message;
  return typeof err === "string" ? err : "unknown error";
}

// Migration SQL files, bundled at build time. Validated at runtime so no
// type assertion is needed on vite's glob return type.
const migrationFiles: Record<string, string> = Object.fromEntries(
  Object.entries(
    import.meta.glob("../../drizzle/*.sql", {
      query: "?raw",
      import: "default",
      eager: true,
    }),
  ).filter((entry): entry is [string, string] => typeof entry[1] === "string"),
);

export class SqlitePersistence implements Persistence {
  private constructor(
    private sqlite: Database,
    private db: ReturnType<typeof drizzle>,
  ) {}

  static async open(): Promise<SqlitePersistence> {
    const sqlite = await Database.load(DB_URL);
    const db = drizzle(async (sql, params, method) => {
      if (method === "run") {
        await sqlite.execute(sql, params);
        return { rows: [] };
      }
      // Fallback path for any select routed through Drizzle: positional
      // rows via Object.values (key order = column order from the driver).
      const rows = await sqlite.select<Record<string, unknown>[]>(sql, params);
      const values = rows.map((r) => Object.values(r));
      return { rows: method === "get" ? (values[0] ?? []) : values };
    });
    const p = new SqlitePersistence(sqlite, db);
    await p.migrate();
    return p;
  }

  /**
   * Apply pending drizzle-kit migrations, tracked in __migrations.
   *
   * A file and its bookkeeping row go over the wire as ONE execute()
   * string wrapped in BEGIN/COMMIT. Statement-at-a-time was not atomic:
   * a file that fails half-way (a unique index that real data violates,
   * or the process being killed mid-file, which is routine on Android)
   * left its earlier statements committed with no __migrations row, and
   * since the generated SQL uses bare CREATE TABLE every later launch
   * re-ran statement 1 and died on "table already exists" — permanently.
   *
   * BEGIN and COMMIT must travel together: the plugin runs each
   * execute() on a connection from an sqlx pool, so sending them as
   * separate calls can put them on different connections.
   */
  private async migrate(): Promise<void> {
    await this.sqlite.execute(
      "CREATE TABLE IF NOT EXISTS __migrations (name TEXT PRIMARY KEY, applied_at TEXT NOT NULL)",
    );
    const appliedRows = await this.sqlite.select<{ name: string }[]>(
      "SELECT name FROM __migrations",
    );
    const applied = new Set(appliedRows.map((r) => r.name));

    // Repair devices damaged by the pre-0.5.7 migrator, which ran statements
    // one at a time and wrote its bookkeeping row only after the whole file
    // succeeded. A failure part-way through left real tables behind with no
    // __migrations row, and because the generated SQL is bare CREATE TABLE,
    // every later launch died on "table already exists" — permanently, with
    // no way out of the error screen. If the first migration is unapplied but
    // its tables already exist, adopt them instead of re-running the file.
    const names = Object.keys(migrationFiles).sort();
    const first = names[0]?.split("/").pop();
    if (first && !applied.has(first)) {
      const existing = await this.sqlite.select<{ name: string }[]>(
        "SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'exercises'",
      );
      if (existing.length > 0) {
        await this.sqlite.execute(
          "INSERT OR IGNORE INTO __migrations (name, applied_at) VALUES ($1, $2)",
          [first, new Date().toISOString()],
        );
        applied.add(first);
      }
    }

    for (const path of names) {
      const name = path.split("/").pop() ?? path;
      if (applied.has(name)) continue;
      const stmts = (migrationFiles[path] ?? "")
        .split("--> statement-breakpoint")
        .map((raw) => raw.trim())
        .filter((stmt) => stmt !== "")
        .map((stmt) => (stmt.endsWith(";") ? stmt : `${stmt};`));
      // Values are inlined, not bound: a parameter list applies to the
      // first statement of a multi-statement query only.
      stmts.push(
        `INSERT INTO __migrations (name, applied_at) VALUES (${quote(name)}, ${quote(new Date().toISOString())});`,
      );
      try {
        await this.sqlite.execute(`BEGIN;\n${stmts.join("\n")}\nCOMMIT;`);
      } catch (err) {
        // No explicit ROLLBACK. The failing statement aborts before COMMIT
        // so nothing from this file is durable, and SQLite discards the open
        // transaction when the connection closes — which is exactly what a
        // relaunch does. Issuing one here would be a guess anyway: the sqlx
        // pool can hand it a different connection than the one that ran the
        // batch. A failed migration is already a hard stop (we throw, the
        // app shows the error card, nothing else writes), and the backfill
        // above recovers databases damaged before this was transactional.
        throw new Error(`Migration ${name} failed: ${errorText(err)}`);
      }
    }
  }

  /** SELECT * from a table, mapped to Drizzle's TS field names. */
  private async all<Row extends Record<string, unknown>>(
    table: SQLiteTable,
  ): Promise<Row[]> {
    const cols = Object.entries(getTableColumns(table));
    const rows = await this.sqlite.select<Record<string, unknown>[]>(
      `SELECT * FROM "${getTableName(table)}"`,
    );
    return rows.map((row) => {
      const out: Record<string, unknown> = {};
      for (const [ts, col] of cols) {
        let v = row[col.name];
        if (col.columnType === "SQLiteBoolean") v = !!v;
        out[ts] = v === null ? undefined : v;
      }
      return out as Row;
    });
  }

  async load(): Promise<AppData> {
    const exerciseRows = await this.all<{
      id: string; name: string; category: string; metric: string;
      muscles: string; builtIn: boolean;
    }>(t.exercises);

    if (exerciseRows.length === 0) {
      // Fresh DB: seed, importing any legacy localStorage data.
      const legacy =
        typeof localStorage !== "undefined"
          ? localStorage.getItem(STORAGE_KEY)
          : null;
      const initial = loadData(); // parses legacy blob or seeds fresh
      await this.persistAll(initial);
      if (legacy !== null) {
        localStorage.setItem(`${STORAGE_KEY}.imported`, legacy);
        localStorage.removeItem(STORAGE_KEY);
      }
      return initial;
    }

    const [splitRows, dayRows, dayExRows, sessionRows, entryRows, setRows, prRows] =
      await Promise.all([
        this.all<{ id: string; name: string; description?: string; builtIn: boolean }>(t.splits),
        this.all<{ id: string; splitId: string; name: string; position: number }>(t.splitDays),
        this.all<{ dayId: string; exerciseId: string; position: number }>(t.splitDayExercises),
        this.all<{
          id: string; name: string; date: string; finishedAt?: string;
          splitId?: string; splitDayId?: string; templateId?: string; note?: string;
        }>(t.sessions),
        this.all<{ id: string; sessionId: string; exerciseId: string; position: number; note?: string }>(t.sessionEntries),
        this.all<{
          id: string; entryId: string; sessionId: string; position: number;
          weight?: number; reps?: number; seconds?: number; meters?: number;
          rpe?: number; done: boolean;
        }>(t.workoutSets),
        this.all<{
          id: string; exerciseId: string; kind: string; value: number; reps?: number;
          date: string; sessionId?: string; note?: string; manual: boolean;
        }>(t.personalRecords),
      ]);

    const byPos = <X extends { position: number }>(a: X, b: X) => a.position - b.position;
    const groupPush = <V,>(m: Map<string, V[]>, k: string, v: V) => {
      const arr = m.get(k);
      if (arr) arr.push(v);
      else m.set(k, [v]);
    };

    const daysBySplit = new Map<string, typeof dayRows>();
    for (const d of dayRows) {
      groupPush(daysBySplit, d.splitId, d);
    }
    const exByDay = new Map<string, typeof dayExRows>();
    for (const de of dayExRows) {
      groupPush(exByDay, de.dayId, de);
    }
    const entriesBySession = new Map<string, typeof entryRows>();
    for (const e of entryRows) {
      groupPush(entriesBySession, e.sessionId, e);
    }
    const setsByEntry = new Map<string, typeof setRows>();
    for (const s of setRows) {
      groupPush(setsByEntry, s.entryId, s);
    }

    const data: AppData = {
      version: 1,
      exercises: exerciseRows.map((e) => ({
        id: e.id,
        name: e.name,
        category: e.category as Exercise["category"],
        metric: e.metric as Exercise["metric"],
        muscles: JSON.parse(e.muscles || "[]") as string[],
        builtIn: e.builtIn,
      })),
      splits: splitRows.map((s) => ({
        id: s.id,
        name: s.name,
        description: s.description,
        builtIn: s.builtIn,
        days: (daysBySplit.get(s.id) ?? []).sort(byPos).map((d) => ({
          id: d.id,
          name: d.name,
          exerciseIds: (exByDay.get(d.id) ?? []).sort(byPos).map((x) => x.exerciseId),
        })),
      })),
      sessions: sessionRows
        .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
        .map((s) => ({
          id: s.id,
          name: s.name,
          date: s.date,
          finishedAt: s.finishedAt,
          splitId: s.splitId,
          splitDayId: s.splitDayId,
          templateId: s.templateId,
          note: s.note,
          entries: (entriesBySession.get(s.id) ?? []).sort(byPos).map((e) => ({
            id: e.id,
            exerciseId: e.exerciseId,
            note: e.note,
            sets: (setsByEntry.get(e.id) ?? []).sort(byPos).map((w) => ({
              id: w.id,
              weight: w.weight,
              reps: w.reps,
              seconds: w.seconds,
              meters: w.meters,
              rpe: w.rpe,
              done: w.done,
            })),
          })),
        })),
      prs: prRows.map((p) => ({
        id: p.id,
        exerciseId: p.exerciseId,
        kind: p.kind as PersonalRecord["kind"],
        value: p.value,
        reps: p.reps,
        date: p.date,
        sessionId: p.sessionId,
        note: p.note,
        manual: p.manual,
      })),
    };

    // Built-ins shipped in an app update are not in this device's DB yet.
    // Without this, a new template's stations silently do not exist and
    // the workout runs short. Merge, then write the new rows through.
    const knownExercises = new Set(data.exercises.map((e) => e.id));
    const knownSplits = new Set(data.splits.map((s) => s.id));
    mergeBuiltIns(data);
    for (const ex of data.exercises) {
      if (!knownExercises.has(ex.id)) await this.saveExercise(ex);
    }
    for (const sp of data.splits) {
      if (!knownSplits.has(sp.id)) await this.saveSplit(sp);
    }

    return data;
  }

  /** Used when seeding a fresh DB (or importing legacy data). */
  private async persistAll(data: AppData): Promise<void> {
    for (const ex of data.exercises) await this.saveExercise(ex);
    for (const sp of data.splits) await this.saveSplit(sp);
    for (const s of data.sessions) await this.saveSession(s);
    await this.replacePRs(data.prs);
  }

  async saveExercise(ex: Exercise): Promise<void> {
    const row = {
      id: ex.id,
      name: ex.name,
      category: ex.category,
      metric: ex.metric,
      muscles: JSON.stringify(ex.muscles),
      builtIn: ex.builtIn,
    };
    await this.db
      .insert(t.exercises)
      .values(row)
      .onConflictDoUpdate({ target: t.exercises.id, set: row });
  }

  async deleteExercise(id: string): Promise<void> {
    await this.db.delete(t.exercises).where(eq(t.exercises.id, id));
  }

  async saveSplit(split: Split): Promise<void> {
    const row = {
      id: split.id,
      name: split.name,
      description: split.description ?? null,
      builtIn: split.builtIn,
    };
    await this.db
      .insert(t.splits)
      .values(row)
      .onConflictDoUpdate({ target: t.splits.id, set: row });

    // Upsert then prune — never the reverse. Deleting the day structure
    // first autocommits, so a rejected insert (SQLITE_BUSY, the WebView
    // suspended mid-IPC) or an Android process kill in that window left the
    // split permanently empty: mergeBuiltIns only adds splits whose id is
    // MISSING, and the id survives, so nothing ever repaired it.
    //
    // Deduped on (dayId, exerciseId), the table's primary key. A day listing
    // the same exercise twice is a UNIQUE violation inside load(); db-smoke
    // rejects it in seed content, but splits are user-editable so the write
    // path must not be fatal either.
    const dayEx: { dayId: string; exerciseId: string; position: number }[] = [];
    for (const d of split.days) {
      const seen = new Set<string>();
      for (const exId of d.exerciseIds) {
        if (seen.has(exId)) continue;
        seen.add(exId);
        dayEx.push({ dayId: d.id, exerciseId: exId, position: seen.size - 1 });
      }
    }

    if (split.days.length > 0) {
      await this.db
        .insert(t.splitDays)
        .values(
          split.days.map((d, i) => ({
            id: d.id,
            splitId: split.id,
            name: d.name,
            position: i,
          })),
        )
        .onConflictDoUpdate({
          target: t.splitDays.id,
          set: {
            splitId: sql`excluded.split_id`,
            name: sql`excluded.name`,
            position: sql`excluded.position`,
          },
        });
    }
    if (dayEx.length > 0) {
      await this.db
        .insert(t.splitDayExercises)
        .values(dayEx)
        .onConflictDoUpdate({
          target: [t.splitDayExercises.dayId, t.splitDayExercises.exerciseId],
          set: { position: sql`excluded.position` },
        });
    }

    // Only now remove what actually disappeared. Both deletes are scoped to
    // this split, so a concurrent edit to another split is untouched.
    const dayIds = split.days.map((d) => d.id);
    const keptPairs = new Set(dayEx.map((x) => `${x.dayId} ${x.exerciseId}`));
    const staleRows = await this.sqlite.select<
      { day_id: string; exercise_id: string }[]
    >(
      `SELECT sde.day_id, sde.exercise_id FROM split_day_exercises sde
         JOIN split_days sd ON sd.id = sde.day_id
        WHERE sd.split_id = $1`,
      [split.id],
    );
    for (const r of staleRows) {
      if (keptPairs.has(`${r.day_id} ${r.exercise_id}`)) continue;
      await this.db
        .delete(t.splitDayExercises)
        .where(
          and(
            eq(t.splitDayExercises.dayId, r.day_id),
            eq(t.splitDayExercises.exerciseId, r.exercise_id),
          ),
        );
    }
    await this.db
      .delete(t.splitDays)
      .where(
        dayIds.length > 0
          ? and(
              eq(t.splitDays.splitId, split.id),
              notInArray(t.splitDays.id, dayIds),
            )
          : eq(t.splitDays.splitId, split.id),
      );
  }

  async deleteSplit(id: string): Promise<void> {
    await this.db.delete(t.splitDayExercises).where(
      inArray(
        t.splitDayExercises.dayId,
        this.db
          .select({ id: t.splitDays.id })
          .from(t.splitDays)
          .where(eq(t.splitDays.splitId, id)),
      ),
    );
    await this.db.delete(t.splitDays).where(eq(t.splitDays.splitId, id));
    await this.db.delete(t.splits).where(eq(t.splits.id, id));
  }

  /**
   * Ids still on disk, optionally limited to one session, so a write can
   * delete exactly what disappeared instead of clearing and refilling.
   */
  private async idsOnDisk(table: string, sessionId?: string): Promise<Set<string>> {
    const rows =
      sessionId === undefined
        ? await this.sqlite.select<{ id: string }[]>(`SELECT id FROM "${table}"`)
        : await this.sqlite.select<{ id: string }[]>(
            `SELECT id FROM "${table}" WHERE session_id = $1`,
            [sessionId],
          );
    return new Set(rows.map((r) => r.id));
  }

  /**
   * Upsert the session and everything under it, then delete only the
   * rows that are actually gone.
   *
   * This used to DELETE the session's sets and entries and then insert
   * them back. Every execute() is its own autocommit statement on a
   * pooled connection, so there was no transaction around that pair: a
   * rejected insert (SQLITE_BUSY, the OS suspending the WebView mid-IPC)
   * left the session row on disk with zero entries and zero sets, and
   * the work was gone. Upsert-then-prune has no such window — a failure
   * mid-way leaves the previous rows intact and the diff is replayed.
   */
  async saveSession(session: Session): Promise<void> {
    const row = {
      id: session.id,
      name: session.name,
      date: session.date,
      finishedAt: session.finishedAt ?? null,
      splitId: session.splitId ?? null,
      splitDayId: session.splitDayId ?? null,
      templateId: session.templateId ?? null,
      note: session.note ?? null,
    };
    await this.db
      .insert(t.sessions)
      .values(row)
      .onConflictDoUpdate({ target: t.sessions.id, set: row });

    // Entries before sets: workout_sets.entry_id is a foreign key.
    if (session.entries.length > 0) {
      await this.db
        .insert(t.sessionEntries)
        .values(
          session.entries.map((e, i) => ({
            id: e.id,
            sessionId: session.id,
            exerciseId: e.exerciseId,
            position: i,
            note: e.note ?? null,
          })),
        )
        .onConflictDoUpdate({
          target: t.sessionEntries.id,
          set: {
            sessionId: sql`excluded.session_id`,
            exerciseId: sql`excluded.exercise_id`,
            position: sql`excluded.position`,
            note: sql`excluded.note`,
          },
        });
    }
    const sets = session.entries.flatMap((e) =>
      e.sets.map((w, i) => ({
        id: w.id,
        entryId: e.id,
        sessionId: session.id,
        position: i,
        weight: w.weight ?? null,
        reps: w.reps ?? null,
        seconds: w.seconds ?? null,
        meters: w.meters ?? null,
        rpe: w.rpe ?? null,
        done: w.done,
      })),
    );
    if (sets.length > 0) {
      await this.db
        .insert(t.workoutSets)
        .values(sets)
        .onConflictDoUpdate({
          target: t.workoutSets.id,
          set: {
            entryId: sql`excluded.entry_id`,
            sessionId: sql`excluded.session_id`,
            position: sql`excluded.position`,
            weight: sql`excluded.weight`,
            reps: sql`excluded.reps`,
            seconds: sql`excluded.seconds`,
            meters: sql`excluded.meters`,
            rpe: sql`excluded.rpe`,
            done: sql`excluded.done`,
          },
        });
    }

    // Sets first: deleting an entry cascades to its sets anyway, but the
    // reverse order would drop rows we are about to keep.
    const keptSets = new Set(sets.map((s) => s.id));
    const goneSets = [...(await this.idsOnDisk("workout_sets", session.id))]
      .filter((id) => !keptSets.has(id));
    if (goneSets.length > 0) {
      await this.db.delete(t.workoutSets).where(inArray(t.workoutSets.id, goneSets));
    }
    const keptEntries = new Set(session.entries.map((e) => e.id));
    const goneEntries = [...(await this.idsOnDisk("session_entries", session.id))]
      .filter((id) => !keptEntries.has(id));
    if (goneEntries.length > 0) {
      await this.db.delete(t.sessionEntries).where(inArray(t.sessionEntries.id, goneEntries));
    }
  }

  async deleteSession(id: string): Promise<void> {
    await this.db.delete(t.workoutSets).where(eq(t.workoutSets.sessionId, id));
    await this.db.delete(t.sessionEntries).where(eq(t.sessionEntries.sessionId, id));
    await this.db.delete(t.sessions).where(eq(t.sessions.id, id));
  }

  /**
   * Upsert then prune, never empty-then-refill. Manually entered PRs
   * exist nowhere else in the app — auto ones are recomputed from the
   * sessions, but a manual record wiped by a failed insert is gone for
   * good. Auto PR ids are stable (`auto-<exercise>:<kind>`), so a
   * recompute that changes nothing writes the same rows back.
   */
  async replacePRs(prs: PersonalRecord[]): Promise<void> {
    if (prs.length > 0) {
      await this.db
        .insert(t.personalRecords)
        .values(
          prs.map((p) => ({
            id: p.id,
            exerciseId: p.exerciseId,
            kind: p.kind,
            value: p.value,
            reps: p.reps ?? null,
            date: p.date,
            sessionId: p.sessionId ?? null,
            note: p.note ?? null,
            manual: p.manual,
          })),
        )
        .onConflictDoUpdate({
          target: t.personalRecords.id,
          set: {
            exerciseId: sql`excluded.exercise_id`,
            kind: sql`excluded.kind`,
            value: sql`excluded.value`,
            reps: sql`excluded.reps`,
            date: sql`excluded.date`,
            sessionId: sql`excluded.session_id`,
            note: sql`excluded.note`,
            manual: sql`excluded.manual`,
          },
        });
    }
    const kept = new Set(prs.map((p) => p.id));
    const gone = [...(await this.idsOnDisk("personal_records"))].filter((id) => !kept.has(id));
    if (gone.length > 0) {
      await this.db.delete(t.personalRecords).where(inArray(t.personalRecords.id, gone));
    }
  }
}
