/**
 * SQLite persistence via tauri-plugin-sql, with Drizzle as the ORM.
 *
 * - Schema lives in ./schema.ts; migrations are generated by drizzle-kit
 *   into /drizzle and applied here at startup (tracked in __migrations).
 * - Writes go through Drizzle's query builder (typed against the schema)
 *   executed over the plugin.
 * - Reads use plain `SELECT *` mapped by column NAME using Drizzle's
 *   table metadata. (The sqlite-proxy driver wants positional rows, but
 *   the plugin returns name-keyed objects — mapping by name is the only
 *   ordering-safe bridge, so selects deliberately bypass the proxy.)
 */
import Database from "@tauri-apps/plugin-sql";
import { drizzle } from "drizzle-orm/sqlite-proxy";
import { eq, getTableColumns, getTableName, inArray } from "drizzle-orm";
import type { SQLiteTable } from "drizzle-orm/sqlite-core";
import type {
  AppData,
  Exercise,
  PersonalRecord,
  Session,
  Split,
  Units,
} from "../types";
import { loadData, STORAGE_KEY } from "../lib/store";
import type { Persistence } from "./persistence";
import * as t from "./schema";

const DB_URL = "sqlite:varg.db";

// Migration SQL files, bundled at build time.
const migrationFiles = import.meta.glob("../../drizzle/*.sql", {
  query: "?raw",
  import: "default",
  eager: true,
}) as Record<string, string>;

export class SqlitePersistence implements Persistence {
  private constructor(
    private sqlite: Database,
    private db: ReturnType<typeof drizzle>,
  ) {}

  static async open(): Promise<SqlitePersistence> {
    const sqlite = await Database.load(DB_URL);
    const db = drizzle(async (sql, params, method) => {
      if (method === "run") {
        await sqlite.execute(sql, params);
        return { rows: [] };
      }
      // Fallback path for any select routed through Drizzle: positional
      // rows via Object.values (key order = column order from the driver).
      const rows = await sqlite.select<Record<string, unknown>[]>(sql, params);
      const values = rows.map((r) => Object.values(r));
      return { rows: method === "get" ? (values[0] ?? []) : values };
    });
    const p = new SqlitePersistence(sqlite, db);
    await p.migrate();
    return p;
  }

  /** Apply pending drizzle-kit migrations, tracked in __migrations. */
  private async migrate(): Promise<void> {
    await this.sqlite.execute(
      "CREATE TABLE IF NOT EXISTS __migrations (name TEXT PRIMARY KEY, applied_at TEXT NOT NULL)",
    );
    const appliedRows = await this.sqlite.select<{ name: string }[]>(
      "SELECT name FROM __migrations",
    );
    const applied = new Set(appliedRows.map((r) => r.name));
    for (const path of Object.keys(migrationFiles).sort()) {
      const name = path.split("/").pop()!;
      if (applied.has(name)) continue;
      for (const raw of migrationFiles[path].split("--> statement-breakpoint")) {
        const stmt = raw.trim();
        if (stmt) await this.sqlite.execute(stmt);
      }
      await this.sqlite.execute(
        "INSERT INTO __migrations (name, applied_at) VALUES ($1, $2)",
        [name, new Date().toISOString()],
      );
    }
  }

  /** SELECT * from a table, mapped to Drizzle's TS field names. */
  private async all<Row extends Record<string, unknown>>(
    table: SQLiteTable,
  ): Promise<Row[]> {
    const cols = Object.entries(getTableColumns(table));
    const rows = await this.sqlite.select<Record<string, unknown>[]>(
      `SELECT * FROM "${getTableName(table)}"`,
    );
    return rows.map((row) => {
      const out: Record<string, unknown> = {};
      for (const [ts, col] of cols) {
        let v = row[col.name];
        if (col.columnType === "SQLiteBoolean") v = !!v;
        out[ts] = v === null ? undefined : v;
      }
      return out as Row;
    });
  }

  async load(): Promise<AppData> {
    const exerciseRows = await this.all<{
      id: string; name: string; category: string; metric: string;
      muscles: string; builtIn: boolean;
    }>(t.exercises);

    if (exerciseRows.length === 0) {
      // Fresh DB: seed, importing any legacy localStorage data.
      const hadLegacy =
        typeof localStorage !== "undefined" &&
        localStorage.getItem(STORAGE_KEY) !== null;
      const initial = loadData(); // parses legacy blob or seeds fresh
      await this.persistAll(initial);
      if (hadLegacy) {
        localStorage.setItem(`${STORAGE_KEY}.imported`, localStorage.getItem(STORAGE_KEY)!);
        localStorage.removeItem(STORAGE_KEY);
      }
      return initial;
    }

    const [splitRows, dayRows, dayExRows, sessionRows, entryRows, setRows, prRows, settingRows] =
      await Promise.all([
        this.all<{ id: string; name: string; description?: string; builtIn: boolean }>(t.splits),
        this.all<{ id: string; splitId: string; name: string; position: number }>(t.splitDays),
        this.all<{ dayId: string; exerciseId: string; position: number }>(t.splitDayExercises),
        this.all<{
          id: string; name: string; date: string; finishedAt?: string;
          splitId?: string; splitDayId?: string; templateId?: string; note?: string;
        }>(t.sessions),
        this.all<{ id: string; sessionId: string; exerciseId: string; position: number; note?: string }>(t.sessionEntries),
        this.all<{
          id: string; entryId: string; sessionId: string; position: number;
          weight?: number; reps?: number; seconds?: number; meters?: number;
          rpe?: number; done: boolean;
        }>(t.workoutSets),
        this.all<{
          id: string; exerciseId: string; kind: string; value: number; reps?: number;
          date: string; sessionId?: string; note?: string; manual: boolean;
        }>(t.personalRecords),
        this.all<{ key: string; value: string }>(t.settings),
      ]);

    const byPos = <X extends { position: number }>(a: X, b: X) => a.position - b.position;

    const daysBySplit = new Map<string, typeof dayRows>();
    for (const d of dayRows) {
      (daysBySplit.get(d.splitId) ?? daysBySplit.set(d.splitId, []).get(d.splitId)!).push(d);
    }
    const exByDay = new Map<string, typeof dayExRows>();
    for (const de of dayExRows) {
      (exByDay.get(de.dayId) ?? exByDay.set(de.dayId, []).get(de.dayId)!).push(de);
    }
    const entriesBySession = new Map<string, typeof entryRows>();
    for (const e of entryRows) {
      (entriesBySession.get(e.sessionId) ?? entriesBySession.set(e.sessionId, []).get(e.sessionId)!).push(e);
    }
    const setsByEntry = new Map<string, typeof setRows>();
    for (const s of setRows) {
      (setsByEntry.get(s.entryId) ?? setsByEntry.set(s.entryId, []).get(s.entryId)!).push(s);
    }

    const unitsRow = settingRows.find((s) => s.key === "units");
    const units: Units = unitsRow?.value === "imperial" ? "imperial" : "metric";

    const data: AppData = {
      version: 1,
      units,
      exercises: exerciseRows.map((e) => ({
        id: e.id,
        name: e.name,
        category: e.category as Exercise["category"],
        metric: e.metric as Exercise["metric"],
        muscles: JSON.parse(e.muscles || "[]") as string[],
        builtIn: e.builtIn,
      })),
      splits: splitRows.map((s) => ({
        id: s.id,
        name: s.name,
        description: s.description,
        builtIn: s.builtIn,
        days: (daysBySplit.get(s.id) ?? []).sort(byPos).map((d) => ({
          id: d.id,
          name: d.name,
          exerciseIds: (exByDay.get(d.id) ?? []).sort(byPos).map((x) => x.exerciseId),
        })),
      })),
      sessions: sessionRows
        .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
        .map((s) => ({
          id: s.id,
          name: s.name,
          date: s.date,
          finishedAt: s.finishedAt,
          splitId: s.splitId,
          splitDayId: s.splitDayId,
          templateId: s.templateId,
          note: s.note,
          entries: (entriesBySession.get(s.id) ?? []).sort(byPos).map((e) => ({
            id: e.id,
            exerciseId: e.exerciseId,
            note: e.note,
            sets: (setsByEntry.get(e.id) ?? []).sort(byPos).map((w) => ({
              id: w.id,
              weight: w.weight,
              reps: w.reps,
              seconds: w.seconds,
              meters: w.meters,
              rpe: w.rpe,
              done: w.done,
            })),
          })),
        })),
      prs: prRows.map((p) => ({
        id: p.id,
        exerciseId: p.exerciseId,
        kind: p.kind as PersonalRecord["kind"],
        value: p.value,
        reps: p.reps,
        date: p.date,
        sessionId: p.sessionId,
        note: p.note,
        manual: p.manual,
      })),
    };

    return data;
  }

  /** Used when seeding a fresh DB (or importing legacy data). */
  private async persistAll(data: AppData): Promise<void> {
    await this.saveUnits(data.units);
    for (const ex of data.exercises) await this.saveExercise(ex);
    for (const sp of data.splits) await this.saveSplit(sp);
    for (const s of data.sessions) await this.saveSession(s);
    await this.replacePRs(data.prs);
  }

  async saveUnits(units: Units): Promise<void> {
    await this.db
      .insert(t.settings)
      .values({ key: "units", value: units })
      .onConflictDoUpdate({ target: t.settings.key, set: { value: units } });
  }

  async saveExercise(ex: Exercise): Promise<void> {
    const row = {
      id: ex.id,
      name: ex.name,
      category: ex.category,
      metric: ex.metric,
      muscles: JSON.stringify(ex.muscles),
      builtIn: ex.builtIn,
    };
    await this.db
      .insert(t.exercises)
      .values(row)
      .onConflictDoUpdate({ target: t.exercises.id, set: row });
  }

  async deleteExercise(id: string): Promise<void> {
    await this.db.delete(t.exercises).where(eq(t.exercises.id, id));
  }

  async saveSplit(split: Split): Promise<void> {
    const row = {
      id: split.id,
      name: split.name,
      description: split.description ?? null,
      builtIn: split.builtIn,
    };
    await this.db
      .insert(t.splits)
      .values(row)
      .onConflictDoUpdate({ target: t.splits.id, set: row });

    // Replace day structure wholesale — simple and small.
    await this.db.delete(t.splitDayExercises).where(
      inArray(
        t.splitDayExercises.dayId,
        this.db
          .select({ id: t.splitDays.id })
          .from(t.splitDays)
          .where(eq(t.splitDays.splitId, split.id)),
      ),
    );
    await this.db.delete(t.splitDays).where(eq(t.splitDays.splitId, split.id));

    if (split.days.length > 0) {
      await this.db.insert(t.splitDays).values(
        split.days.map((d, i) => ({
          id: d.id,
          splitId: split.id,
          name: d.name,
          position: i,
        })),
      );
      const dayEx = split.days.flatMap((d) =>
        d.exerciseIds.map((exId, i) => ({
          dayId: d.id,
          exerciseId: exId,
          position: i,
        })),
      );
      if (dayEx.length > 0) {
        await this.db.insert(t.splitDayExercises).values(dayEx);
      }
    }
  }

  async deleteSplit(id: string): Promise<void> {
    await this.db.delete(t.splitDayExercises).where(
      inArray(
        t.splitDayExercises.dayId,
        this.db
          .select({ id: t.splitDays.id })
          .from(t.splitDays)
          .where(eq(t.splitDays.splitId, id)),
      ),
    );
    await this.db.delete(t.splitDays).where(eq(t.splitDays.splitId, id));
    await this.db.delete(t.splits).where(eq(t.splits.id, id));
  }

  async saveSession(session: Session): Promise<void> {
    const row = {
      id: session.id,
      name: session.name,
      date: session.date,
      finishedAt: session.finishedAt ?? null,
      splitId: session.splitId ?? null,
      splitDayId: session.splitDayId ?? null,
      templateId: session.templateId ?? null,
      note: session.note ?? null,
    };
    await this.db
      .insert(t.sessions)
      .values(row)
      .onConflictDoUpdate({ target: t.sessions.id, set: row });

    await this.db.delete(t.workoutSets).where(eq(t.workoutSets.sessionId, session.id));
    await this.db.delete(t.sessionEntries).where(eq(t.sessionEntries.sessionId, session.id));

    if (session.entries.length > 0) {
      await this.db.insert(t.sessionEntries).values(
        session.entries.map((e, i) => ({
          id: e.id,
          sessionId: session.id,
          exerciseId: e.exerciseId,
          position: i,
          note: e.note ?? null,
        })),
      );
      const sets = session.entries.flatMap((e) =>
        e.sets.map((w, i) => ({
          id: w.id,
          entryId: e.id,
          sessionId: session.id,
          position: i,
          weight: w.weight ?? null,
          reps: w.reps ?? null,
          seconds: w.seconds ?? null,
          meters: w.meters ?? null,
          rpe: w.rpe ?? null,
          done: w.done,
        })),
      );
      if (sets.length > 0) {
        await this.db.insert(t.workoutSets).values(sets);
      }
    }
  }

  async deleteSession(id: string): Promise<void> {
    await this.db.delete(t.workoutSets).where(eq(t.workoutSets.sessionId, id));
    await this.db.delete(t.sessionEntries).where(eq(t.sessionEntries.sessionId, id));
    await this.db.delete(t.sessions).where(eq(t.sessions.id, id));
  }

  async replacePRs(prs: PersonalRecord[]): Promise<void> {
    await this.db.delete(t.personalRecords);
    if (prs.length > 0) {
      await this.db.insert(t.personalRecords).values(
        prs.map((p) => ({
          id: p.id,
          exerciseId: p.exerciseId,
          kind: p.kind,
          value: p.value,
          reps: p.reps ?? null,
          date: p.date,
          sessionId: p.sessionId ?? null,
          note: p.note ?? null,
          manual: p.manual,
        })),
      );
    }
  }
}
